package lotto.model

// TODO: Generated by RandomNumberGenerator
class LottoTicket(val lottoNumbers: Numbers) {
    val cost: Int = COST_OF_TICKET

    init {
        require(cost == COST_OF_TICKET) { "Cost of Ticket should be $COST_OF_TICKET" }
        require(lottoNumbers.size == SIZE_OF_NUMBERS) { "Size of numbers should be $SIZE_OF_NUMBERS" }
        require(
            lottoNumbers.all { it >= MIN_LOTTO_NUMBER && it <= MAX_LOTTO_NUMBER },
        ) { "All numbers should be in the range [$MIN_LOTTO_NUMBER, $MAX_LOTTO_NUMBER]" }
    }

    companion object {
        const val COST_OF_TICKET = 1000
        const val SIZE_OF_NUMBERS = 6
        const val MIN_LOTTO_NUMBER = 1
        const val MAX_LOTTO_NUMBER = 45
    }
}
