package lotto.controller

import lotto.model.LottoTicketGenerator
import lotto.model.Tickets
import lotto.model.WinningNumbers
import lotto.model.WinningStatistics
import lotto.view.InputValidator
import lotto.view.InputView
import lotto.view.ResultView

class LottoController(
    private val inputView: InputView,
    private val inputValidator: InputValidator,
    private val resultView: ResultView,
    private val lottoTicketGenerator: LottoTicketGenerator,
    private val winningStatistics: WinningStatistics,
) {
    private fun processTickets(
        purchaseAmount: Int,
        numberOfManualTickets: Int,
    ): Tickets {
        val numberOfAutoGeneratedTickets =
            lottoTicketGenerator.generateNumberOfTickets(purchaseAmount, numberOfManualTickets)
        val manualTickets = inputView.readManualTickets(numberOfManualTickets)
        val tickets =
            lottoTicketGenerator
                .generateTickets(
                    manualTickets,
                    numberOfAutoGeneratedTickets,
                )
        resultView
            .printNumberOfTickets(
                numberOfManualTickets,
                numberOfAutoGeneratedTickets,
            )
        resultView.printTickets(tickets)
        return Tickets(tickets)
    }

    private fun processResult(
        tickets: Tickets,
        winningNumbers: WinningNumbers,
        bonusNumber: Int,
    ) {
        val result = winningStatistics.calculateResult(tickets, winningNumbers, bonusNumber)
        resultView.printStatistics(result)
    }

    private fun processReturnRate(purchaseAmount: Int) {
        val returnRate = winningStatistics.calculateReturnRate(purchaseAmount)
        resultView.printReturnRate(returnRate)
    }

    fun run() {
        val purchaseAmount = inputView.readPurchaseAmount()
        inputValidator.validatePurchaseAmount(purchaseAmount)
        val numberOfManualTickets = inputView.readManualNumberOfTickets()
        inputValidator.validateManualTicketAmount(purchaseAmount, numberOfManualTickets)
        val tickets = processTickets(purchaseAmount, numberOfManualTickets)
        val winningNumbers = inputView.readWinningNumbers()
        inputValidator.validateWinningNumbers(winningNumbers)
        val bonusNumber = inputView.readBonusNumber()
        inputValidator.validateBonusNumber(bonusNumber, winningNumbers)
        processResult(tickets, winningNumbers, bonusNumber)
        processReturnRate(purchaseAmount)
    }
}
